version: '2.2'

services:
  elasticsearch-master:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch-master
    environment:
      - cluster.name=docker-elasticsearch-cluster
      - node.name=master
      - bootstrap.memory_lock=true
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet

  elasticsearch-slave1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch-slave1
    restart: always
    environment:
      - cluster.name=docker-elasticsearch-cluster
      - node.name=slave1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "discovery.zen.ping.unicast.hosts=elasticsearch-master"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet

  elasticsearch-head:
    restart: always
    image: mobz/elasticsearch-head:5
    container_name: elasticsearch-head
    depends_on:
      - elasticsearch-master
    ports:
      - 9100:9100

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet: